Hunterise 1.13.10
hunter-packages/rosconsole pull request #3
Opened 2019-06-11 17:03 UTC by kgeorgiev93

Applied hunterisation changes from 1.13.7. However, I found an issue with those changes.

There are three backend libraries that can be used for the logging - log4cxx, glog or print.
Log4cxx is the default and comes from the system because it has not been hunterised.
Glog has been hunterised and the changes from 1.13.7 are supposed to link against the target. But it doesn't quite work - instead when compiling and installing locally I could see hardcoded paths to my hunter cache that point to the library. As far as I am aware, this breaks relocatability. Furthermore, the ros::rosconsole_glog target was not linked against glog so you would get linker errors when a package depends on rosconsole.

I have pushed another commit on top of the initial changes that fix those issues.

@lsolanka it would be great if you could also have a look at those changes.

If it is necessary I could rebase and squash those commits to make the history a bit cleaner. I kept it like this for now so that the fix for the above issues is more visible.

2019-06-19 08:05 UTC, ruslo requested changes
> If it is necessary I could rebase and squash those commits to make the history a bit cleaner

Yes, please do

2019-06-20 22:11 UTC, kgeorgiev93 commented
Rebased.

2019-06-21 11:22 UTC, ruslo approved these changes

2019-06-21 11:22 UTC, merged

2019-06-21 11:22 UTC, ruslo commented
Released: https://github.com/hunter-packages/rosconsole/releases/tag/v1.13.10-p0